# Generated by Django 5.0.6 on 2024-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.TextField()),
                ('ANS', models.TextField()),
            ],
        ),
    ]
