# Generated by Django 5.0.6 on 2024-07-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=120)),
                ('msg', models.TextField()),
            ],
        ),
    ]
