# Generated by Django 5.0.6 on 2024-07-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='usrdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Pw', models.CharField(max_length=50)),
            ],
        ),
    ]
