# Generated by Django 5.0.6 on 2024-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0004_usrdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrdata',
            name='id',
        ),
        migrations.AddField(
            model_name='usrdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usrdata',
            name='edufld',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usrdata',
            name='edulvl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usrdata',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
