# Generated by Django 5.0.6 on 2024-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0005_remove_usrdata_id_usrdata_dob_usrdata_edufld_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrdata',
            name='Pw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
