# Generated by Django 5.0.6 on 2024-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0008_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrdata',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
