# Generated by Django 5.0.6 on 2024-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0009_usrdata_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
                ('img', models.ImageField(null=True, upload_to=None)),
            ],
        ),
    ]
