# Generated by Django 5.0.6 on 2024-10-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0010_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
