# Generated by Django 5.0.6 on 2024-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0011_hospital_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
