# Generated by Django 5.0.6 on 2024-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0012_alter_hospital_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
