# Generated by Django 5.0.6 on 2024-10-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0013_disease_description_disease_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='diets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('diet', models.TextField()),
            ],
        ),
    ]
