# Generated by Django 5.0.6 on 2025-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0014_diets'),
    ]

    operations = [
        migrations.CreateModel(
            name='med',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=25)),
                ('med', models.TextField()),
            ],
        ),
    ]
