# Generated by Django 5.0.6 on 2025-04-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0015_med'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrdata',
            name='img',
        ),
    ]
