# Generated by Django 5.0.6 on 2025-04-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0016_remove_usrdata_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('msg', models.TextField()),
            ],
        ),
    ]
