# Generated by Django 5.0.6 on 2025-04-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstapp', '0017_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='med',
            old_name='med',
            new_name='medi',
        ),
    ]
